/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RatanpurScaling;


import com.itextpdf.text.BaseColor;
import java.io.FileOutputStream;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Font.FontFamily;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;


import java.io.*;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;




/**
 *
 * @author Admin
 */
public class FromDate extends javax.swing.JFrame {

    /**
     * Creates new form FromDate
     */
    public FromDate() {
        initComponents();
        makediretory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fromtf = new javax.swing.JTextField();
        todatetf = new javax.swing.JTextField();
        subbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 11)); // NOI18N
        jLabel1.setText("From Date (yyyy-mm-dd)");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 11)); // NOI18N
        jLabel2.setText("To Date (yyyy-mm-dd)");

        fromtf.setFont(new java.awt.Font("Times New Roman", 2, 11)); // NOI18N

        todatetf.setFont(new java.awt.Font("Times New Roman", 2, 11)); // NOI18N

        subbtn.setText("Submit");
        subbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subbtnActionPerformed(evt);
            }
        });

        jButton1.setText("Back to Home Page");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fromtf, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(todatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subbtn)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromtf, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(todatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subbtn)
                    .addComponent(jButton1))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subbtnActionPerformed
        // TODO add your handling code here:
        
        String from = String.valueOf(fromtf.getText().toString());
        
        String to = String.valueOf(todatetf.getText().toString());
        
       Document document = new Document();
        try {
            PdfWriter.getInstance(document, new FileOutputStream("C:\\pdfscale\\"+from +" "+to + ".pdf"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FromDate.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(FromDate.class.getName()).log(Level.SEVERE, null, ex);
        }
        document.open();
        Font f=new Font(FontFamily.TIMES_ROMAN,10.0f,Font.ITALIC,BaseColor.RED);
        try {
            document.add(new Paragraph("MODERN STEEL MILLS LIMITED.\n 199 BAIZID BOSTAMIA \n CHITTAGONG,BANGLADESH",f));
        } catch (DocumentException ex) {
            Logger.getLogger(FromDate.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        try {
            document.add(new Paragraph("\n\n\n"));
        } catch (DocumentException ex) {
            Logger.getLogger(FromDate.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         PdfPTable table = new PdfPTable(10);
         
          table.addCell(new Phrase("Id", FontFactory.getFont(FontFactory.TIMES_ITALIC, 6)));

         table.addCell(new Phrase("Item Name", FontFactory.getFont(FontFactory.TIMES_ITALIC, 6)));

         
         table.addCell(new Phrase("Challan No", FontFactory.getFont(FontFactory.TIMES_ITALIC, 6)));


             
         
       table.addCell(new Phrase("In. Date", FontFactory.getFont(FontFactory.TIMES_ITALIC, 6)));

        
         table.addCell(new Phrase("Out. Date", FontFactory.getFont(FontFactory.TIMES_ITALIC, 6)));
        table.addCell(new Phrase("Rece./Sen.", FontFactory.getFont(FontFactory.TIMES_ITALIC, 6)));

        table.addCell(new Phrase("VEHICLE ID", FontFactory.getFont(FontFactory.TIMES_ITALIC, 6)));
        table.addCell(new Phrase("Tare Weight", FontFactory.getFont(FontFactory.TIMES_ITALIC, 6)));

         table.addCell(new Phrase("Gross Weight", FontFactory.getFont(FontFactory.TIMES_ITALIC, 6)));
         table.addCell(new Phrase("Net Weight", FontFactory.getFont(FontFactory.TIMES_ITALIC, 6)));
         

        try {
            document.add(table);
        } catch (DocumentException ex) {
            Logger.getLogger(FromDate.class.getName()).log(Level.SEVERE, null, ex);
        }
          
           
          
          try{
              
              Connection conn = ConnectDB.WENSDB();
              
              String sql = "SELECT * from scale_data ORDER BY ID DESC";
              
              Statement stmt = conn.createStatement();
              ResultSet rslt = stmt.executeQuery(sql);
              
              int i=0;
              while(rslt.next()){
                  
                  
                  String date1 = rslt.getTimestamp("DATE_TIME").toString();
                  String datte = String.valueOf(date1.substring(0, 10));
                  
                  PdfPTable table1 = new PdfPTable(10);
                
                  if(datte.compareTo(from)>=0 && datte.compareTo(to)<=0){
                 table1.addCell(new Phrase(String.valueOf(rslt.getInt("ID")), FontFactory.getFont(FontFactory.TIMES_ITALIC, 6)));
                 table1.addCell(new Phrase(String.valueOf(rslt.getString("ITEM_NAME")), FontFactory.getFont(FontFactory.TIMES_ITALIC, 6)));

                 table1.addCell(new Phrase(String.valueOf(rslt.getString("CHALLAN_NO")), FontFactory.getFont(FontFactory.TIMES_ITALIC, 6)));
                 table1.addCell(new Phrase(String.valueOf(rslt.getTimestamp("DATE_TIME")), FontFactory.getFont(FontFactory.TIMES_ITALIC, 6)));
                 table1.addCell(new Phrase(String.valueOf(rslt.getDate("UPDATED_ON")), FontFactory.getFont(FontFactory.TIMES_ITALIC, 6)));
                 table1.addCell(new Phrase(String.valueOf(rslt.getString("NAME")), FontFactory.getFont(FontFactory.TIMES_ITALIC, 6)));
                 table1.addCell(new Phrase(String.valueOf(rslt.getString("CONTACT_NUMBER")), FontFactory.getFont(FontFactory.TIMES_ITALIC, 6)));
                 table1.addCell(new Phrase(String.valueOf(rslt.getInt("TARE_WEIGHT")), FontFactory.getFont(FontFactory.TIMES_ITALIC, 6)));
                 table1.addCell(new Phrase(String.valueOf(rslt.getInt("GROSS_WEIGHT")), FontFactory.getFont(FontFactory.TIMES_ITALIC, 6)));
                 table1.addCell(new Phrase(String.valueOf(rslt.getInt("WEIGHT")), FontFactory.getFont(FontFactory.TIMES_ITALIC, 6)));

                  document.add(table1);
                  }
                  
                  

              }
              
          }catch(Exception e){
              
            //  e.printStackTrace();
              
              
          }
        
        document.close();
        fromtf.setText("");
        todatetf.setText("");
        
    }//GEN-LAST:event_subbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        dispose();
        HomePage hp =new HomePage();
        hp.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    
      public  void makediretory(){
        
         File file = new File("C:\\pdfscale");
        if (!file.exists()) {
            if (file.mkdir()) {
              //  System.out.println("Directory is created!");
            } else {
              //  System.out.println("Failed to create directory!");
            }
        }
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromDate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fromtf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton subbtn;
    private javax.swing.JTextField todatetf;
    // End of variables declaration//GEN-END:variables
}
