/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RatanpurScaling;

import gnu.io.CommPortIdentifier;
import gnu.io.PortInUseException;
import gnu.io.SerialPort;
import gnu.io.SerialPortEvent;
import gnu.io.SerialPortEventListener;
import gnu.io.UnsupportedCommOperationException;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.Scanner;
import java.util.TooManyListenersException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;


/**
 *
 * @author MOSTAFA
 */
public class ReceiveDataFromScaleForOfline extends javax.swing.JFrame implements Runnable ,SerialPortEventListener {

    // declare object............
    static CommPortIdentifier portId;
    static Enumeration portList;
    public HashMap portMap = new HashMap();

    InputStream inputStream;
    SerialPort serialPort;
    Thread readThread;
    ArrayList<String> list = new ArrayList<>();
    Connection con = null;
    ResultSet rs = null;
    int cnt=0;
//set  baudrate from comboBox......... 
    public static int baudrate;

    void setbaudrate(int a) {
        baudrate = a;
        //System.out.println(bbb);
    }

    public ReceiveDataFromScaleForOfline() {
        initComponents();     
     //   setChallan();
     //   setItem();
      //  setCustomer();
      //  transportID();
//        companyName();
        fetch();
    }

    /* public void setItem() {
       
         try{
              con = ConnectDB.WENSDB();
              String sql = "SELECT NAME  FROM ITEMFORSCALE" ;
                         
               java.sql.Statement select = con.createStatement();
              rs = select.executeQuery(sql);
            while (rs.next()) {
                String pat = rs.getString("NAME");
               // System.out.println(pat);
                comitem.addItem(pat);
            }
        }
        catch(Exception e){
           
        }
    
    
    }*/
   /*  public void setCustomer() {
       
         try{
              con = ConnectDB.WENSDB();
              String sql = "SELECT NAME  FROM CUSORSUPPLIER" ;
                         
               java.sql.Statement select = con.createStatement();
              rs = select.executeQuery(sql);
            while (rs.next()) {
                String pat = rs.getString("NAME");
                comcus.addItem(pat);
            }
        }
        catch(Exception e){
           
        }
    
    
    }*/
     
    /*  public void transportID() {
       
         try{
              con = ConnectDB.WENSDB();
              String sql = "SELECT NAME  FROM transport" ;
                         
               java.sql.Statement select = con.createStatement();
              rs = select.executeQuery(sql);
            while (rs.next()) {
                String pat = rs.getString("NAME");
              //  comtrnsid.addItem(pat);
            }
        }
        catch(Exception e){
           
        }
    
    
    }*/
    
    public void setChallan() {
       
         try{
              con = ConnectDB.WENSDB();
              String sql = "SELECT CHALLAN_ID DIS, CHALLAN_ID RET FROM CHALLAN_MST C " +
                            "WHERE NOT EXISTS " +
                            "(SELECT * FROM SCALE_DATA S WHERE S.CHALLAN_NO=C.CHALLAN_ID) " +
                                "ORDER BY CHALLAN_ID ASC";
               java.sql.Statement select = con.createStatement();
              rs = select.executeQuery(sql);
         /*   while (rs.next()) {
                String pat = rs.getString("RET");
                jComboBox1.addItem(pat);
            }*/
        }
        catch(Exception e){
           
        }
    
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxBR = new javax.swing.JComboBox<>();
        jComboBoxDB = new javax.swing.JComboBox<>();
        jComboBoxSB = new javax.swing.JComboBox<>();
        jComboBoxPB = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldWeightS = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBoxPort = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextFieldTare = new javax.swing.JTextField();
        jTextFieldGross = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNetWeight = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldTrname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldScaleNo = new javax.swing.JTextField();
        saveToDB = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxCMname = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabelscaleUser = new javax.swing.JLabel();
        jLabeRimage = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldUnitPrice = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        tfchallan = new javax.swing.JTextField();
        tftrnsid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comcus = new javax.swing.JTextField();
        comitem = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jToolBar1.setRollover(true);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ratanpur Digital Scale Automation System", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(153, 153, 255))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(153, 153, 255));
        jPanel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ratanpur Group Scale Automation");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Setting", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jComboBoxBR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boud Rate" }));

        jComboBoxDB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Data Bits" }));

        jComboBoxSB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Stop Bits" }));

        jComboBoxPB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Parity Bits" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxBR, 0, 104, Short.MAX_VALUE)
                    .addComponent(jComboBoxDB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxSB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxPB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxBR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxSB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Control Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jButton2.setText("Run");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Stable");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Back to Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Weight Scale Value", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jTextFieldWeightS.setEditable(false);
        jTextFieldWeightS.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldWeightS.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextFieldWeightS.setForeground(new java.awt.Color(102, 255, 102));
        jTextFieldWeightS.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldWeightS, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldWeightS, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setText("Search Ports");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBoxPort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Port" }));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("Tare>>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Gross>>");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTextFieldTare.setEditable(false);

        jTextFieldGross.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Net Weight:");

        jTextFieldNetWeight.setEditable(false);

        jLabel2.setText("Challan No:");

        jLabel3.setText("Receiver/Sender Name");

        jLabel4.setText("Transport ID ");

        jLabel7.setText("Item Name:");

        jLabel8.setText("Remarks");

        jLabel9.setText("Customer ID : ");

        jLabel5.setText("Scale No:");

        jTextFieldScaleNo.setEditable(false);
        jTextFieldScaleNo.setText("BAIZID SCALE");

        saveToDB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveToDB.setText("Save");
        saveToDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveToDBActionPerformed(evt);
            }
        });

        jLabel10.setText("ID:");

        jLabel11.setText("Company Name:");

        jComboBoxCMname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RSRM", "MSML" }));

        jLabel12.setText("User Name");

        jLabeRimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RatanpurScaling/r.pur1.PNG"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Unit Price");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Receiver", "Sender" }));

        jLabel6.setText("Transport Name : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(390, 390, 390))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfchallan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comitem, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                                    .addComponent(saveToDB)
                                    .addGap(41, 41, 41)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButton7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                            .addComponent(jTextFieldGross, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGap(20, 20, 20)))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextFieldUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextFieldTare, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 311, Short.MAX_VALUE)
                                    .addComponent(jComboBoxPort, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldScaleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(413, 413, 413)
                                        .addComponent(jTextFieldNetWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tftrnsid, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                            .addComponent(comcus))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(71, 71, 71)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldTrname, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCMname, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jLabelscaleUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabeRimage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabelscaleUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(comcus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(tfchallan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)))
                                .addGap(0, 3, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(comitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(20, 20, 20))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addComponent(jComboBoxPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(tftrnsid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jTextFieldTrname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldScaleNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jTextFieldUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldTare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldGross, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldNetWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveToDB)))
                        .addGap(60, 60, 60))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxCMname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabeRimage, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTable1.setBackground(new java.awt.Color(153, 153, 153));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Scale No", "Name", "Challan No", "Tare Weight", "Gross Weight", "Net Weight", "Date", "Item Name", "Transport Name", "Contant No", "Company", "Unit Price", "Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, true, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveToDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToDBActionPerformed
        // save to Database
        String idno;
        idno = jTextFieldID.getText(); int trww=0 ,grss=0;
        if(!idno.isEmpty()){
           
            
             try {
            con = orclconnectoff.getCon();
            String sql = "select * from SCALE_DATA WHERE ID='" + idno + "'";
            java.sql.Statement select = con.createStatement();
            rs = select.executeQuery(sql);
            
            while (rs.next()) {
               trww=rs.getInt("TARE_WEIGHT");
               grss=rs.getInt("GROSS_WEIGHT");
            }
        } catch (Exception e) {
        }
            
            
        }
        
        if(trww!=0){
            jTextFieldTare.setText(String.valueOf(trww));
        }
        if(grss!=0){
            jTextFieldGross.setText(String.valueOf(grss));
        }

        try {
            
            
            
            String cn = tfchallan.getText();
            String name = comcus.getText();
            
            String conno = tftrnsid.getText().toString();
            
            String itemN = comitem.getText();
           
            String trN = jTextFieldTrname.getText();
            
            
            String remark = jComboBox2.getSelectedItem().toString();
            String add = jTextFieldAddress.getText();
            String trw=null,grs=null;
            
            trw = jTextFieldTare.getText();
            grs = jTextFieldGross.getText();
           
            String scale = jTextFieldScaleNo.getText();
            String comp_id = jComboBoxCMname.getSelectedItem().toString();
            String nw = jTextFieldNetWeight.getText();
            int netwI = Integer.valueOf(nw);
            double unitPrice=0,totalPrice=0;
            try{
             String utp = jTextFieldUnitPrice.getText();
             unitPrice = Double.valueOf(utp);
              totalPrice = unitPrice * netwI;
            }catch(Exception e){}
            
      
            
            

           

            stblV = jTextFieldWeightS.getText();
            String sclw = stblV.replaceAll("[^0-9]", "");
            int scale_weight = Integer.valueOf(sclw);

            idno = jTextFieldID.getText();
            String identify=null;
          
            if (idno.isEmpty()) {
               // System.out.println("hjfg");
               
              Connection cnt = orclconnectoff.getCon();
              String sql = "SELECT COUNT(*) from SCALE_DATA";
              Statement stmt= cnt.createStatement();
              ResultSet result= stmt.executeQuery(sql);
              int p=0;
              while(result.next()){
                  p=result.getInt("COUNT(*)");
              }
                p=p+1;
           
                       // System.out.print(cn+name+conno+itemN+trN+remark+add+trw+grs+scale+comp_id+nw);
                       identify="N";
                    ValueWriteOnOfline.data(p,scale_weight, cn, name, conno, itemN, trN, remark, add, trw, grs, scale, user, comp_id, netwI, unitPrice, totalPrice,identify);// send values for insert into database......
                    fetch();// retrieve value from database for display into Jtable..........
                
            } else {
                try {
                    
                    int trweight = Integer.valueOf(trw);
                    int grossweight = Integer.valueOf(grs);
                    int id_no = Integer.valueOf(idno);
                    String updt=null;
                    
                  
                    try {
            con = orclconnectoff.getCon();
            String sql = "select * from SCALE_DATA WHERE ID='" + idno + "'";
            java.sql.Statement select = con.createStatement();
            rs = select.executeQuery(sql);
            int unit_price=0;
            
            while (rs.next()) {
               trww=rs.getInt("TARE_WEIGHT");
               grss=rs.getInt("GROSS_WEIGHT");
               unitPrice =rs.getDouble("RATE");
            }
        } catch (Exception e) {
        }
                    int neti=0;
                    if(trww==0){
                       neti = Math.abs(grss-trweight);
                    }else{
                        neti = Math.abs(trww-grossweight);
                    }
                    
                    Double Total_amount=(Double) (unitPrice*neti);
                    jTextFieldNetWeight.setText(String.valueOf(neti));
                       
                    updt = "UPDATE SCALE_DATA SET GROSS_WEIGHT='" + grossweight + "', TARE_WEIGHT='" + trweight + "',WEIGHT='" + neti + "',TOTAL_AMOUNT='" + Total_amount + "',IDENTIFY='N' WHERE ID='" + id_no + "'";

                    
                    
                    
                  // updt = "UPDATE SCALE_DATA SET GROSS_WEIGHT='" + grossweight + "',WEIGHT='" + netwI + "',TOTAL_AMOUNT='" + totalPrice + "' WHERE ID='" + id_no + "'";

                   
                    

                    Connection con1 = orclconnectoff.getCon();
                    java.sql.Statement stm = con1.createStatement();
                    rs = stm.executeQuery(updt);

                    fetch();
                    //call database
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
        } catch (Exception e) {
                System.out.println(e);
        }
        //fetch();
    }//GEN-LAST:event_saveToDBActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // get gross weight ...........

        stblV = jTextFieldWeightS.getText();
        int tare=0;
        try {
            String gross = stblV.replaceAll("[^0-9]", "");// get only numeric values.......
            grs = Integer.valueOf(gross);
            jTextFieldGross.setText(String.valueOf(grs));

           // netw = Math.abs(grs - tare);
            
             String idno = jTextFieldID.getText();
            if(idno.isEmpty()){
            jTextFieldNetWeight.setText(String.valueOf(grs));
            }else{
             try {
            con = orclconnectoff.getCon();
            String sql = "select * from SCALE_DATA WHERE ID='" + idno + "'";
            java.sql.Statement select = con.createStatement();
            rs = select.executeQuery(sql);
            int unit_price=0;
            
            while (rs.next()) {
               
               tare=rs.getInt("GROSS_WEIGHT");
               
               
            }
        } catch (Exception e) {
        }
               jTextFieldNetWeight.setText(String.valueOf(Math.abs(tare-grs))); 
            }
            
          //  jTextFieldNetWeight.setText(String.valueOf(netw));
          //  jTextFieldWeightS.setText("");

        } catch (Exception e) {
        }
        serialPort.close();
        jButton3ActionPerformed(evt);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // get tare weight...........
        stblV = jTextFieldWeightS.getText();
        //test....
        //String  tr=jTextFieldTare.getText();
        int grss=0;
        try {

            String tr = stblV.replaceAll("[^0-9]", "");
            tare = Integer.valueOf(tr);
            jTextFieldTare.setText(String.valueOf(tare));

         //   netw = Math.abs(grs - tare);
            
            String idno = jTextFieldID.getText();
            if(idno.isEmpty()){
            jTextFieldNetWeight.setText(String.valueOf(tare));
            }
            else{
                
                   try {
            con = orclconnectoff.getCon();
            String sql = "select * from SCALE_DATA WHERE ID='" + idno + "'";
            java.sql.Statement select = con.createStatement();
            rs = select.executeQuery(sql);
            int unit_price=0;
            
            while (rs.next()) {
               
               grss=rs.getInt("GROSS_WEIGHT");
               
               
            }
        } catch (Exception e) {
        }
               jTextFieldNetWeight.setText(String.valueOf(Math.abs(grss-tare))); 
            }

// set net weight......
           // jTextFieldWeightS.setText("");

        } catch (Exception e) {
        }
         serialPort.close();
        jButton3ActionPerformed(evt);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // search port from computer

        portList = CommPortIdentifier.getPortIdentifiers();// get serial ports....
        String[] prts = new String[5];
        String[] a = new String[5]; //set port value automatically
        String[] b = new String[5];
        String[] c = new String[5];
        String[] d = new String[5];//.......
        int i = 0;
        while (portList.hasMoreElements()) {
            portId = (CommPortIdentifier) portList.nextElement();
            if (portId.getPortType() == CommPortIdentifier.PORT_SERIAL) {// port type
                prts[i] = portId.getName();
                jComboBoxPort.addItem(portId.getName());
                portMap.put(portId.getName(), portId);
                i++;
            }
        }
      
        try {
             
            int bb = 9600; // set boudrate...........
           // System.out.println(bb);
           
      
            a[0] = String.valueOf(bb);
            int db = SerialPort.DATABITS_7;
            b[0] = String.valueOf(db);
            int sb = SerialPort.STOPBITS_1;
            c[0] = String.valueOf(sb);
            int p = SerialPort.PARITY_EVEN;
            d[0] = String.valueOf(p);
            
        } catch (Exception e) {
        }
        //jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Port" }));
        jComboBoxBR.setModel(new javax.swing.DefaultComboBoxModel<>(a));
        jComboBoxDB.setModel(new javax.swing.DefaultComboBoxModel<>(b));
        jComboBoxSB.setModel(new javax.swing.DefaultComboBoxModel<>(c));
        jComboBoxPB.setModel(new javax.swing.DefaultComboBoxModel<>(d));

        //
        jComboBoxPort.setModel(new javax.swing.DefaultComboBoxModel<>(prts));// set value into comboBox......
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    public final void setComPortTimeouts(){
        
    }
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        dispose();
        HomePage hp = new HomePage();
        hp.setUser(jLabelscaleUser.getText());
        hp.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    @Override
    public void run() {
        try{
            Thread.sleep(20000);
        }catch(InterruptedException e){
        }
    }
    
    String scale;
    public void setScale(String scale){
        this.scale=scale;
       // System.out.println(scale);
       
     //   jTextFieldScaleNo.setText(scale);
     //   System.out.println(jTextFieldScaleNo.getText());
    }
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // clear text field

        jTextFieldWeightS.setText("");
        jTextFieldGross.setText("");
        jTextFieldTare.setText("");
        jTextFieldNetWeight.setText("");
        jTextFieldID.setText("");
        tftrnsid.setText("");
       // jTextFieldCNo.setText("");
       // jTextFieldName.setText("");
      //  jTextFieldConNo.setText("");
      //  jTextFieldItemN.setText("");
        jTextFieldTrname.setText("");
       // jTextFieldRemark.setText("");
        jTextFieldAddress.setText("");
        tare = 0;
        grs = 0;
        netw = 0;

        jButton2ActionPerformed(evt);//re-open Application

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //close all inputs....

        try {
            serialPort.removeEventListener();
            serialPort.close();
            inputStream.close();
            jTextFieldWeightS.setText("0");
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // setting Serial Port

        String port = jComboBoxPort.getSelectedItem().toString();

        String br = jComboBoxBR.getSelectedItem().toString();
        int baudR = Integer.valueOf(br);
        String db = jComboBoxDB.getSelectedItem().toString();
        int dataB = Integer.valueOf(db);
        String sb = jComboBoxSB.getSelectedItem().toString();
        int stopB = Integer.valueOf(sb);

        String prb = jComboBoxPB.getSelectedItem().toString();
        int pb = 0;
        if (prb.equals("EVEN")) {
            pb = 2;
        } else if (prb.equals("ODD")) {
            pb = 1;
        } else {
            pb = 0;
        }

        portId = (CommPortIdentifier) portMap.get(port);
        try {
            serialPort = (SerialPort) portId.open("DigitalWeightAutomation", 2000); // open serial port
        } catch (PortInUseException e) {
            JOptionPane.showMessageDialog(null, "Port In Use Exception..\n");
          //  jTextFieldWeightS.setText("Port In Use Exception..\n");
        }
        try {
            inputStream = serialPort.getInputStream(); // get input from serial port
        } catch (IOException e) {
               JOptionPane.showMessageDialog(null, "Not response inputStream..\n");
           // jTextFieldWeightS.setText("Not response inputStream..\n");
        }
        try {
            serialPort.addEventListener(this);// open EventListener
        } catch (TooManyListenersException e) {
            JOptionPane.showMessageDialog(null, "Too Many Listeners Exception..\n");
           // jTextFieldWeightS.setText("Too Many Listeners Exception..\n");
        }
        serialPort.notifyOnDataAvailable(true);
        try {
                        serialPort.setSerialPortParams(9600,
                                SerialPort.DATABITS_7,
                                SerialPort.STOPBITS_1,
                                SerialPort.PARITY_EVEN);
           // serialPort.setSerialPortParams(baudR, dataB, stopB, pb); // set serial port
        } catch (UnsupportedCommOperationException e) {
            jTextFieldWeightS.setText("Unsupported CommOperation Exception..\n");
        }
        readThread = new Thread( this);
        readThread.start();

    }//GEN-LAST:event_jButton2ActionPerformed
    public static String stblV = null;
    public static int grs = 0;    public static int tare = 0;
    public int netw = 0;
    String user1;
    public void setUser(String user){
    this.user1 =user;
    }
    
    String scale_no1 = null;

    String challan_no1 = null;

    @Override
    public void serialEvent(SerialPortEvent event) {    /// active event when commport will be pluged............
        switch (event.getEventType()) {
            case SerialPortEvent.BI:  // setting 9 pins.....
            case SerialPortEvent.OE:
            case SerialPortEvent.FE:
            case SerialPortEvent.PE:
            case SerialPortEvent.CD:
            case SerialPortEvent.CTS:
            case SerialPortEvent.DSR:
            case SerialPortEvent.RI:
            case SerialPortEvent.OUTPUT_BUFFER_EMPTY:
                break;
            case SerialPortEvent.DATA_AVAILABLE:// get data from Scale machine.............
                byte[] readBuffer = new byte[1024];

               
                BufferedReader br;
              
                
                
                

                int i = 0,sum=0;
                try {
                    
                     String strm = null;
                     String numberOnly = null,result="";
                     StringBuilder sb=null;
                     int t=0;
                    while (inputStream.available() > 0) { //check input data....
                        int n=inputStream.read(readBuffer);
                        strm = new String(readBuffer,0,n,"UTF-8");
                        
                        
                      for(i=strm.length()-1;i>=0;i--){
                          
                           if(strm.charAt(i)==' ' ) break;
                           else if(strm.charAt(i)>='0' && strm.charAt(i)<='9')
                          {
                              result = result+strm.charAt(i);
                              t=1;
                          }
                         
                         
                          
                      }
                      sb = new StringBuilder(result);
                        sb.reverse().toString();
                       // int cnt=0;
                        if(t==1)
                        {
                            String ss = new String(sb);
                            numberOnly = ss.replace("[^0-9]","");
                           // System.out.println(sb);
                            cnt++;
                            if(cnt>1){
                                if(80000>Integer.valueOf(numberOnly))
                                 jTextFieldWeightS.setText(Integer.valueOf(numberOnly).toString());
                            }
                        }
                        i++;
                    }
           
                   
                  //  System.out.println(Integer.valueOf(sb.toString()));
                    
                    String sss = jTextFieldWeightS.getText();
                   
                   // int t = Integer.valueOf(sss);
                    //serialPort.flush();
                    Thread.sleep(5000);
                   
                    
                 /*   String s = null;
                    for (int j = 0; j < list.size() - 1; j++) {
                        s = list.get(j);
                        if (s.contains(list.get(j + 1)))// get stable value............
                        {
                            scale_no1 = jTextFieldScaleNo.getText();
                            challan_no1 = jTextFieldCNo.getText();

                            jTextFieldWeightS.setText(list.get(j) + "  kg\n");
                            // break;
                            if (!s.equals("0")) // stop raeding zero.....................
                            {
                                ValueWriteIntoDB.dataBackup(scale_no1, challan_no1, s);     // insert data into backup table.........
                            }

                        }
                    }*/

                } catch (IOException e) {
                    jTextFieldWeightS.setText("InputStream is not available..\n");
                } catch (InterruptedException ex) {
            Logger.getLogger(ReceiveDataFromScaleForOfline.class.getName()).log(Level.SEVERE, null, ex);
        }
                break;
        }
    }
    
    public static void waiting(int n){
        long t0,t1;
        t0 = System.currentTimeMillis();
        do{
            t1 = System.currentTimeMillis();
        }while((t1-t0)< (n*1000));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceiveDataFromScaleForOfline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceiveDataFromScaleForOfline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceiveDataFromScaleForOfline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceiveDataFromScaleForOfline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ReceiveDataFromScaleForOfline().setVisible(true);
        });
    }
    public String user = null;

    public void userAndScaleNo(String user, String scale) {
      //  jTextFieldScaleNo.setText(scale);
        jLabelscaleUser.setText(user);
        this.user = user;
      //  this.scale=scale;
     
    }

    public void fetch()// retrieve value from database for display into Jtable..........
    {
        try {
            con = orclconnectoff.getCon();
            String sql = "select * from SCALE_DATA order by id desc";
            java.sql.Statement select = con.createStatement();
            rs = select.executeQuery(sql);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                Object ob[] = {rs.getInt("ID"), rs.getString("SCALE_ID"), rs.getString("NAME"), rs.getString("CHALLAN_NO"), rs.getInt("TARE_WEIGHT"),
                    rs.getInt("GROSS_WEIGHT"), rs.getInt("WEIGHT"), rs.getTimestamp("DATE_TIME"), rs.getString("ITEM_NAME"), rs.getString("TRANSPORT_NAME"),
                    rs.getString("CONTACT_NUMBER"), rs.getString("COMPANY_ID"), rs.getDouble("RATE"), rs.getDouble("TOTAL_AMOUNT")};
                model.addRow(ob);
            }
        } catch (Exception e) {
        }
    }

  /*  public void companyName() {
        try {
            con = ConnectDB.WENSDB();
            String sql = "select * from COMPANY_ACCOUNTS";
            java.sql.Statement select = con.createStatement();
            rs = select.executeQuery(sql);
            while (rs.next()) {
                String com_id = rs.getString("ID");
                jComboBoxCMname.addItem(com_id);
            }
        } catch (Exception e) {
        }
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField comcus;
    private javax.swing.JTextField comitem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBoxBR;
    private javax.swing.JComboBox<String> jComboBoxCMname;
    private javax.swing.JComboBox<String> jComboBoxDB;
    private javax.swing.JComboBox<String> jComboBoxPB;
    private javax.swing.JComboBox<String> jComboBoxPort;
    private javax.swing.JComboBox<String> jComboBoxSB;
    private javax.swing.JLabel jLabeRimage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelscaleUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldGross;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNetWeight;
    public javax.swing.JTextField jTextFieldScaleNo;
    private javax.swing.JTextField jTextFieldTare;
    private javax.swing.JTextField jTextFieldTrname;
    private javax.swing.JTextField jTextFieldUnitPrice;
    private javax.swing.JTextField jTextFieldWeightS;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton saveToDB;
    private javax.swing.JTextField tfchallan;
    private javax.swing.JTextField tftrnsid;
    // End of variables declaration//GEN-END:variables
}
